name: EmpirePets
author: OnesRodriguez
version: 1.0
main: me.onesrodriguez.empirepets.Core
commands:
    empirepet:
        description: Main pet command.
        usage: /empirepet
    command2:
        description: Main pet command.
        usage: /empirepet
    command3:
        description: Main pet command.
        usage: /empirepet
        
